echo "Hello, world!"
echo " Hello world " 
echo " commites " 
echo "commmite 4 " 
echo " commite 5 test email notification " 
echo " commite 9 this time we recieve email notification " 
echo " commite 10 final test " 
